version: '3.7'
services:
  redis-master:
    image: redis:latest
    hostname: redis-master
    volumes:
      - redis_master:/data
    ports:
      - '6379:6379'

  redis-slave:
    image: redis:latest
    hostname: redis-slave
    volumes:
      - redis_slave:/data
    ports:
      - '6479:6479'
    command: redis-server --slaveof redis-master 6379

  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - 7843:7843
    volumes:
      # here you can set your own /home/user/p3x-redis-ui-settings folder
      - /home/user/p3x-redis-ui-settings:/settings

volumes:
  redis_master:
  redis_slave:
