spring:
  data:
    redis:
      lettuce:
        cluster:
          refresh:
            adaptive: true
      cluster:
        max-redirects: 2
        nodes:

springdoc:
  swagger-ui:
    path: /green/swagger-ui.html
    displayRequestDuration: true
    operationsSorter: method
    apisSorter: alpha
  default-produces-media-type: application/json