spring:
  data:
    #  cache:
    #    type: none
    redis:
      #    enable: false
      host:
      port: 6379
      connect-timeout: 3000
      key-prefix: "green.redis.lib:"
      time-to-live: 3600
      username:
      password:
      ssl:
        enabled: true
      disable-peer-verification: true
      eager-initialization: true
      replica:
        nodes:
          - host:
            port: 6379
      client-options:
        socket-options:
          keep-alive:
            enable: true
          connection-timeout: 3
        timeout-options:
          timeout: 10000
      pool:
        enabled: true


springdoc:
  swagger-ui:
    path: /green/swagger-ui.html
    displayRequestDuration: true
    operationsSorter: method
    apisSorter: alpha
  default-produces-media-type: application/json